OrdererOrgs:
  - Name: Orderer
    Domain: payscope.example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.payscope.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1




